<?php

/**
 * DataObject Extension Pattern
 *
 * This template shows how to properly extend auto-generated Pimcore DataObject classes
 * with custom business logic while maintaining the auto-generation workflow.
 */

// ============================================================
// 1. Auto-generated Base Class (DO NOT EDIT!)
// File: var/classes/DataObject/{ClassName}.php
// Generated by Pimcore from Class Definition in Admin GUI
// ============================================================

declare(strict_types=1);

namespace Pimcore\Model\DataObject;

/**
 * Auto-generated class - DO NOT EDIT MANUALLY!
 *
 * This file is regenerated every time you save the class definition
 * in Pimcore Admin GUI or run:
 * bin/console pimcore:deployment:classes-rebuild
 *
 * WARNING: Any manual changes will be lost!
 */
class {ClassName} extends Concrete
{
    // Auto-generated getters and setters
    public function getName(): ?string
    {
        // Implementation
    }

    public function setName(?string $name): static
    {
        // Implementation
    }

    // ... more auto-generated methods
}

// ============================================================
// 2. Class Definition File (DO NOT EDIT!)
// File: var/classes/definition_{ClassName}.php
// Export of class definition from Pimcore Admin GUI
// ============================================================

/*
return [
    'id' => '{ClassId}',
    'name' => '{ClassName}',
    'fields' => [
        [
            'fieldtype' => 'input',
            'name' => 'name',
            'title' => 'Name',
            // ... field configuration
        ],
        // ... more fields
    ],
];
*/

// ============================================================
// 3. Custom Extension Class (EDIT THIS!)
// File: src/{Module}/Domain/DataObject/{ClassName}.php
// Your custom business logic and methods
// ============================================================

declare(strict_types=1);

namespace App\{Module}\Domain\DataObject;

use Pimcore\Model\DataObject\{ClassName} as Generated{ClassName};

/**
 * Custom extension of {ClassName} DataObject
 *
 * This class extends the auto-generated base class and adds
 * project-specific business logic.
 *
 * Pimcore will automatically use this class instead of the base class
 * when you use {ClassName}::getById(), new {ClassName}(), etc.
 */
class {ClassName} extends Generated{ClassName}
{
    /**
     * Get all related children (example custom method)
     *
     * @return {ChildClassName}[]
     */
    public function getChildren(): array
    {
        $listing = new {ChildClassName}\Listing();
        $listing->setCondition('parent{ClassName}__id = ?', [$this->getId()]);
        $listing->setOrderKey('name');

        return $listing->load();
    }

    /**
     * Check if object has specific property (example validation)
     */
    public function hasValidPimId(): bool
    {
        $pimId = $this->getPimId();

        return $pimId !== null && $pimId !== '' && str_starts_with($pimId, 'PIM-');
    }

    /**
     * Get formatted display name (example computed property)
     */
    public function getDisplayName(): string
    {
        return sprintf('%s (%s)', $this->getName(), $this->getPimId());
    }

    /**
     * Custom business logic method
     */
    public function exportToArray(): array
    {
        return [
            'pim_id' => $this->getPimId(),
            'name' => $this->getName(),
            'created_at' => $this->getCreationDate()?->format('Y-m-d H:i:s'),
            'modified_at' => $this->getModificationDate()?->format('Y-m-d H:i:s'),
            // Add more fields as needed
        ];
    }

    /**
     * Override parent method if needed (use carefully!)
     */
    public function save(): static
    {
        // Custom validation before save
        if (!$this->hasValidPimId()) {
            throw new \RuntimeException('Cannot save {ClassName} without valid PIM ID');
        }

        // Call parent save
        return parent::save();
    }
}

// ============================================================
// 4. How Pimcore Resolves the Class
// ============================================================

/*
When you call:
    $object = {ClassName}::getById(123);

Pimcore checks in this order:
    1. App\{Module}\Domain\DataObject\{ClassName}  ← Your custom class
    2. Pimcore\Model\DataObject\{ClassName}        ← Auto-generated base

If custom class exists, Pimcore uses it automatically!
No configuration needed in services.yaml!

Verification:
    $object = {ClassName}::getById(123);
    echo get_class($object);
    // Output: App\{Module}\Domain\DataObject\{ClassName}
*/

// ============================================================
// 5. Service Configuration (Optional, usually not needed)
// File: config/services/{module}.yaml
// ============================================================

/*
services:
    # Usually Pimcore auto-resolves the class, but if you need
    # explicit configuration for type-hinting:

    App\{Module}\Domain\DataObject\{ClassName}:
        autowire: true
        autoconfigure: true

    # Repository that uses the extended class:
    App\{Module}\Domain\Repository\{ClassName}RepositoryInterface:
        class: App\{Module}\Infrastructure\Repository\{ClassName}Repository
        autowire: true
*/

// ============================================================
// 6. Usage Examples
// ============================================================

/*
// Get object (automatically uses extended class)
$object = {ClassName}::getById(123);
var_dump($object instanceof App\{Module}\Domain\DataObject\{ClassName}); // true

// Create new object
$object = new {ClassName}();
$object->setParent(Service::createFolderByPath('/objects'));
$object->setKey('my-object');
$object->setPimId('PIM-CLASS-001');
$object->setName('My Object');
$object->setPublished(true);
$object->save();

// Use custom methods
$children = $object->getChildren();
$displayName = $object->getDisplayName();
$hasValidPimId = $object->hasValidPimId();
$exported = $object->exportToArray();

// Listing also returns extended class instances
$listing = new {ClassName}\Listing();
$objects = $listing->load(); // array of App\{Module}\Domain\DataObject\{ClassName}
*/

// ============================================================
// 7. Best Practices
// ============================================================

/*
✅ DO:
    - Add business logic methods to extended class
    - Add computed properties (getDisplayName)
    - Add custom validation (hasValidPimId)
    - Add data transformation (exportToArray)
    - Override save() if you need pre-save validation

❌ DON'T:
    - Edit auto-generated files (var/classes/)
    - Override too many parent methods (fragile)
    - Add database queries to getters (performance)
    - Forget to call parent::save() when overriding
    - Add heavy computations in constructors

REMEMBER:
    - When class definition changes in GUI, regenerate classes:
      bin/console pimcore:deployment:classes-rebuild
    - Extended class must have same name as generated class
    - Must be in App\{Module}\Domain\DataObject\ namespace
    - Pimcore auto-resolves extended class (no DI config needed)
*/